@ECHO OFF
FOR /F "tokens=1,2delims==" %%x IN (.env) DO (IF NOT "%%y"=="" (SET %%x=%%y))
FOR /F "tokens=1,*delims= " %%a IN ("%*") DO (SET all=%%b)

IF [%~1] equ []            (call shell/run.bat)
IF [%~1] equ [s]           (call shell/stop.bat)
IF [%~1] equ [stop]        (call shell/stop.bat)
IF [%~1] equ [e]           (call shell/exec.bat %all%)
IF [%~1] equ [exec]        (call shell/exec.bat %all%)
IF [%~1] equ [mysql]       (call shell/exec.bat mysql -u%DBUserName% -p%DBUserPass% %all%)
IF [%~1] equ [php]         (call shell/exec.bat php %all%)
IF [%~1] equ [ngrok]       (call shell/ngrok.bat)

IF [%~1] equ [a]           (call shell/dev-laravel.bat)
IF [%~1] equ [add]         (call shell/dev-laravel.bat)
IF [%~1] equ [add-laravel] (call shell/dev-laravel.bat)
IF [%~1] equ [d]           (call shell/dev-laravel.bat)
IF [%~1] equ [dev]         (call shell/dev-laravel.bat)
IF [%~1] equ [dev-laravel] (call shell/dev-laravel.bat)

IF [%~1] equ [l]           (call shell/laravel.bat %all%)
IF [%~1] equ [laravel]     (call shell/laravel.bat %all%)
IF [%~1] equ [art]         (call shell/laravel.bat php artisan %all%)
IF [%~1] equ [artisan]     (call shell/laravel.bat php artisan %all%)
IF [%~1] equ [composer]    (call shell/laravel.bat composer %all%)
IF [%~1] equ [npm]         (call shell/laravel.bat npm %all%)
